global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: coredns
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 15s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - coredns.service.local:9153

