global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: jenkins
    honor_timestamps: true
    scrape_interval: 30s
    scrape_timeout: 15s
    scheme: http
    metrics_path: /prometheus
    static_configs:
    - targets:
      - jenkins.apps.svc.cluster.local
      

