name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:     
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: myuser/myimage
          tags: latest
          dockerfiles: |
            ./Dockerfile
          
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Push the Docker image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
