name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:     
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
  push:
    runs-on: ubuntu-latest
    needs: login
    steps:
      - name: Push the Docker image
        run: |
          ls && pwd
          docker build .  -t ronbrian/prometheus:latest
          docker push ronbrian/prometheus:latest

